import { NextRequest, NextResponse } from 'next/server'
import OpenAI from 'openai'
import { getUserProfile, decrementUserCredits, logCreation } from '@/lib/supabase'

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY || '',
})

export async function POST(request: NextRequest) {
  try {
    const formData = await request.formData()
    const prompt = formData.get('prompt') as string
    const model = formData.get('model') as string
    const imageFile = formData.get('image') as File | null
    const userId = formData.get('userId') as string

    if (!prompt) {
      return NextResponse.json(
        { error: 'Prompt is required' },
        { status: 400 }
      )
    }

    // Check user authentication and credits
    if (!userId) {
      return NextResponse.json(
        { error: 'User ID is required' },
        { status: 400 }
      )
    }

    const { data: userProfile, error: profileError } = await getUserProfile(userId)
    if (profileError || !userProfile) {
      return NextResponse.json(
        { error: 'User profile not found' },
        { status: 404 }
      )
    }

    // Check if user has credits
    if (userProfile.credits_remaining <= 0) {
      return NextResponse.json(
        { error: 'Insufficient credits. Please purchase more credits to continue generating content.' },
        { status: 402 }
      )
    }

    if (!process.env.OPENAI_API_KEY || process.env.OPENAI_API_KEY.startsWith('sk-dummy')) {
      // Decrement user credits even for demo mode
      await decrementUserCredits(userId)

      const demoText = `[DEMO] This is a mock response for the prompt: "${prompt}"\n\nIn a real implementation, this would be generated by ${model} from OpenAI.\n\n${imageFile ? `An image (${imageFile.name}) was also provided for context.` : 'No image was provided.'}\n\nCredits have been deducted. To use real OpenAI API:\n1. Get an API key from https://platform.openai.com/\n2. Replace the dummy key in .env.local\n3. Restart the development server`

      await logCreation({
        user_id: userId,
        type: 'text',
        prompt,
        metadata: { model, mode: 'demo', hasImage: !!imageFile },
        cost_credits: 1
      })

      // Return mock response for demo purposes
      return NextResponse.json({
        text: demoText,
      })
    }

    let messages: any[] = [
      {
        role: 'user',
        content: prompt,
      },
    ]

    // Handle image input for vision models
    if (imageFile) {
      const imageBuffer = await imageFile.arrayBuffer()
      const imageBase64 = Buffer.from(imageBuffer).toString('base64')
      const imageDataUrl = `data:${imageFile.type};base64,${imageBase64}`

      messages = [
        {
          role: 'user',
          content: [
            { type: 'text', text: prompt },
            {
              type: 'image_url',
              image_url: {
                url: imageDataUrl,
              },
            },
          ],
        },
      ]
    }

    const completion = await openai.chat.completions.create({
      model: model,
      messages: messages,
      max_tokens: 1000,
    })

    const text = completion.choices[0]?.message?.content || 'No response generated'

    // Decrement user credits after successful generation
    await decrementUserCredits(userId)
    await logCreation({
      user_id: userId,
      type: 'text',
      prompt,
      metadata: { model, hasImage: !!imageFile, generatedBy: 'OpenAI' },
      cost_credits: 1
    })

    return NextResponse.json({ text })
  } catch (error) {
    console.error('Text generation error:', error)
    return NextResponse.json(
      { error: 'Failed to generate text' },
      { status: 500 }
    )
  }
}