import { NextRequest, NextResponse } from 'next/server'
import OpenAI from 'openai'
import { getUserProfile, decrementUserCredits, logCreation } from '@/lib/supabase'
import { uploadTextContent, isS3Configured } from '@/lib/s3'

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY || '',
})

export async function POST(request: NextRequest) {
  try {
    const formData = await request.formData()
    const prompt = formData.get('prompt') as string
    const model = formData.get('model') as string
    const imageFile = formData.get('image') as File | null
    const userId = formData.get('userId') as string

    if (!prompt) {
      return NextResponse.json(
        { error: 'Prompt is required' },
        { status: 400 }
      )
    }

    // Check user authentication and credits
    if (!userId) {
      return NextResponse.json(
        { error: 'User ID is required' },
        { status: 400 }
      )
    }

    const { data: userProfile, error: profileError } = await getUserProfile(userId)
    if (profileError || !userProfile) {
      return NextResponse.json(
        { error: 'User profile not found' },
        { status: 404 }
      )
    }

    // Check if user has credits
    if (userProfile.credits_remaining <= 0) {
      return NextResponse.json(
        { error: 'Insufficient credits. Please purchase more credits to continue generating content.' },
        { status: 402 }
      )
    }

    if (!process.env.OPENAI_API_KEY || process.env.OPENAI_API_KEY.startsWith('sk-dummy')) {
      // Decrement user credits even for demo mode
      await decrementUserCredits(userId)

      const demoText = `[DEMO] This is a mock response for the prompt: "${prompt}"\n\nIn a real implementation, this would be generated by ${model} from OpenAI.\n\n${imageFile ? `An image (${imageFile.name}) was also provided for context.` : 'No image was provided.'}\n\nCredits have been deducted. To use real OpenAI API:\n1. Get an API key from https://platform.openai.com/\n2. Replace the dummy key in .env.local\n3. Restart the development server`

      await logCreation({
        user_id: userId,
        type: 'text',
        prompt,
        metadata: { model, mode: 'demo', hasImage: !!imageFile },
        cost_credits: 1
      })

      // Return mock response for demo purposes
      return NextResponse.json({
        text: demoText,
      })
    }

    let messages: any[] = [
      {
        role: 'user',
        content: prompt,
      },
    ]

    // Handle image input for vision models
    if (imageFile) {
      const imageBuffer = await imageFile.arrayBuffer()
      const imageBase64 = Buffer.from(imageBuffer).toString('base64')
      const imageDataUrl = `data:${imageFile.type};base64,${imageBase64}`

      messages = [
        {
          role: 'user',
          content: [
            { type: 'text', text: prompt },
            {
              type: 'image_url',
              image_url: {
                url: imageDataUrl,
              },
            },
          ],
        },
      ]
    }

    const completion = await openai.chat.completions.create({
      model: model,
      messages: messages,
      max_tokens: 1000,
    })

    const text = completion.choices[0]?.message?.content || 'No response generated'

    // Store in S3 if configured
    let s3Result = null
    console.log('S3 Configuration Check:')
    console.log('AWS_ACCESS_KEY_ID exists:', !!process.env.AWS_ACCESS_KEY_ID)
    console.log('AWS_SECRET_ACCESS_KEY exists:', !!process.env.AWS_SECRET_ACCESS_KEY)
    console.log('AWS_S3_BUCKET exists:', !!process.env.AWS_S3_BUCKET)
    console.log('AWS_REGION exists:', !!process.env.AWS_REGION)
    console.log('isS3Configured():', isS3Configured())

    if (isS3Configured()) {
      try {
        console.log('Attempting to upload text to S3...')
        s3Result = await uploadTextContent(userId, text, {
          prompt,
          model,
          hasImage: !!imageFile
        })
        console.log('Text uploaded to S3 successfully:', s3Result.key)
        console.log('S3 Public URL:', s3Result.publicUrl)
        console.log('S3 Signed URL:', s3Result.url)
      } catch (s3Error) {
        console.error('S3 upload failed:', s3Error)
        console.error('S3 Error details:', s3Error instanceof Error ? s3Error.message : s3Error)
        // Continue without S3 - don't fail the generation
      }
    } else {
      console.log('S3 not configured - skipping upload')
    }

    // Decrement user credits after successful generation
    await decrementUserCredits(userId)
    await logCreation({
      user_id: userId,
      type: 'text',
      prompt,
      metadata: {
        model,
        hasImage: !!imageFile,
        generatedBy: 'OpenAI',
        s3Key: s3Result?.key,
        s3Url: s3Result?.publicUrl
      },
      cost_credits: 1
    })

    return NextResponse.json({
      text,
      downloadUrl: s3Result?.url || null,
      storageKey: s3Result?.key || null
    })
  } catch (error) {
    console.error('Text generation error:', error)
    return NextResponse.json(
      { error: 'Failed to generate text' },
      { status: 500 }
    )
  }
}